version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHID=${CHID}
      - SUDO=${SUDO}
      - FSUB=${FSUB}
      - MONGO_URI=${MONGO_URI}
